### ISSUE TITLE
Cannot import name 'xdc_aggregate' from partially initialized module 'xdatbus' (most likely due to a circular import)

### ISSUE THREAD

**Issue by yyan107** [jcwang587/xdatbus#32]
Hi,

Thanks for sharing the tool!

I have accounted the following error on "cannot import the xdatbus". I have pip install xdatbus with 3.12.0 python in the created environment and it is running in Bash.

I am hoping to get insight from this. Thank you in advance!

Here is the details of the error:

(myenv) yuyan@perlmutter:login34:~/bin/xdatbus/examples> pip install xdatbus
Requirement already satisfied: xdatbus in /global/homes/y/yuyan/.conda/envs/myenv/lib/python3.12/site-packages (0.0.43)
(myenv) yuyan@perlmutter:login34:~/bin/xdatbus/examples> python
Python 3.12.0 | packaged by Anaconda, Inc. | (main, Oct  2 2023, 17:29:18) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xdatbus
  File "<stdin>", line 1
    from xdatbus
                ^
SyntaxError: invalid syntax
>>> import xdatbus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/u2/y/yuyan/bin/xdatbus/examples/xdatbus.py", line 2, in <module>
    from xdatbus import xdc_aggregate, xdc_unwrap
ImportError: cannot import name 'xdc_aggregate' from partially initialized module 'xdatbus' (most likely due to a circular import) (/global/u2/y/yuyan/bin/xdatbus/examples/xdatbus.py)

**Comment by jcwang587** [comment]
Thank you for testing and trying out the package. Please ensure you have the latest build version. The project is still in its very early stages, and I hadn't anticipated users trying it out at this point. However, I'm delighted to share it and answer any questions about this initial version of the tool.

From the error information, it seems there might be a circular import issue. This typically happens when, for instance, Module A imports Module B and Module B, in turn, imports Module A.

If I understand the situation correctly, you might have a file named `xdatbus.py` in the same location where you are trying to import the `xdatbus` package. If this is the case, you could resolve the issue by renaming your main code file to something other than `xdatbus.py`.

This is my first experience publishing a Python package online, so I'm actively learning and striving to release a stable version as soon as possible. Please let me know if you have any other questions!

**Comment by yuyan-ou** [comment]
Hi. Thank you again for sharing the tool and answering the question. I have finally made it run on my local window PC. And I like it since it would recognize the order of XDATCAR by the number followed the underscore. I have attached a example at the end.
Here is sharing my workflow to install it. For those who uses Anaconda on their PC.  Check your visual studio are installed C++build (I use 2019). Go find it here: https://visualstudio.microsoft.com/
Open anaconda prompt, type the following
`conda create -n xdatbus python=3.10.0 ipython`
'pip install xdatbus' 
'pip install jupyternotebook'
When it is all done with No redflag(errors), you are good to start with the first example. 
'jupyter notebook \xdatbus\examples\basics.ipynb'
Please note the output generate at the upper level of your working folder. If you dont like it, u can change the output_dir.
Then have fun!

A example I ran on my XDATCAR file. it start with the first one which is 1000 in my case and go to the next one(named with a larger number)
- Wrapping XDATCAR_1000 ...
Number of frames in XDATCAR_1000: 1000
Wrapping XDATCAR_1300 ...
Number of frames in XDATCAR_1300: 3889

**Comment by jcwang587** [comment]
@yuyan-ou Hi, I am very happy you like this tool, and thank you for sharing your experience using it. Also, the latest codes now include entry points for functions including combining trajectories (`xdc_aggregate`) and checking energies / temperatures (`thermal_report`), which allows to run from command line on terminal, like perlmutter you are using. To get started, it's recommended to first create a conda environment and then install the package with `pip install -U xdatbus`.

- Combine Trajectories
  - Copy the XDATCAR files in sequence, naming as XDATCAR01, XDATCAR02, XDATCAR10 ... or XDATCAR1, XDATCAR2, XDATCAR10...; both formats will work
  - In the same directory, run the command `xdc_aggregate` or use `xdc_aggregate -h` for help.
  - The script will first wrap the coordinates within the cell and concatenate the trajectories using a naming sequence.
```
$ xdc_aggregate
xdatbus-func | xdc_aggregate: Wrapping XDATCAR0 ...
xdatbus-func | xdc_aggregate: number of frames: 2000
xdatbus-func | xdc_aggregate: Wrapping XDATCAR1 ...
xdatbus-func | xdc_aggregate: number of frames: 2000
xdatbus-func | xdc_aggregate: Appending XDATCAR1 ...
sequence:  ['XDATCAR0', 'XDATCAR1']
xdatbus-func | xdc_aggregate: Done!
```
- Check Energies / Temperatures
  - Copy the OSZICAR files in sequence, like XDATCAR
  - In the same directory, run the command `thermal_report` or use `thermal_report -h` for help.
  - The script will export four-column .csv data with potential energy, kinetic energy, total energy, and temperature for each time step.
```
$ thermal_report
xdatbus-func | energy_report: Processing OSZICAR0
xdatbus-func | energy_report: Processing OSZICAR1
xdatbus-func | energy_report: Done!
```
Thank you again for using the tool. We hope to include more functions in the future. Please feel free to share any analysis needed that could be useful in your work.
